name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: location
          run: pwd

        - name: location
          run: ls

        - name: Build with Make
          run: make maven-build

        - name: Build with Make
          run: make maven-build

        - name: Build with Make
          run: make run